---
product:
  name: "Camel Extensions for Quarkus Third Party Components"
  abbreviation: "quarkus-cxf-third-party"
  stage: "GA"
  issueTrackerUrl: "https://issues.redhat.com/projects/CEQ"
version: "2.13.3"
milestone: "CR2"
group: "CXF Extensions for Quarkus Third Party Components"
defaultBuildParameters:
  brewPullActive: false
builds:
- name: "com.fasterxml.woodstox-woodstox-core-6.5.1-AUTOBUILD"
  project: "FasterXML-woodstox"
  buildScript: "# Autobuilder copied this Build Config from BC #11052 rev 2656766\n\
    # This build configuration was modified by Autobuilder\n# Autobuilder copied this\
    \ Build Config from BC #10638 rev 2651661\nmvn '-DskipTests' '-DperformRelease'\
    \ '-Dadditionalparam=-Xdoclint:none' -DaltDeploymentRepository=indy-mvn::${AProxDeployUrl}\
    \ 'deploy'"
  scmUrl: "https://github.com/FasterXML/woodstox.git"
  scmRevision: "woodstox-core-6.5.1"
  environmentName: "OpenJDK 11.0.10+9; Mx 5.259.0; Mvn 3.6.0"
  dependencies:
  - "com.fasterxml-oss-parent-50-AUTOBUILD"
  - "org.codehaus.woodstox-stax2-api-4.2.1-AUTOBUILD"
  brewPullActive: false
  buildType: "MVN"
- name: "io.quarkiverse.cxf-quarkus-cxf-bom-1.5.14-AUTOBUILD"
  project: "quarkiverse/quarkus-cxf"
  buildScript: "# Autobuilder copied this Build Config from BC #11053 rev 2656767\n\
    # This build configuration was modified by Autobuilder\n# Autobuilder copied this\
    \ Build Config from BC #11048 rev 2656673\nmvn clean deploy -DskipTests"
  scmUrl: "https://github.com/quarkiverse/quarkus-cxf.git"
  scmRevision: "1.5.14"
  environmentName: "OpenJDK 11.0; RHEL 8; Mvn 3.8.6; gcc-cpp; make"
  buildPodMemory: 12.0
  brewPullActive: false
  buildType: "MVN"
- name: "io.quarkiverse.xmlsec-quarkus-xmlsec-1.1.2-AUTOBUILD"
  project: "io.quarkiverse.xmlsec-quarkus-xmlsec"
  buildScript: "# This script was autogenerated\nmvn deploy"
  scmUrl: "https://github.com/quarkiverse/quarkus-xmlsec.git"
  scmRevision: "1.1.2"
  description: "Autobuild genearted config for io.quarkiverse.xmlsec:quarkus-xmlsec:1.1.2"
  environmentName: "OpenJDK 11.0; Mvn 3.5.4"
  dependencies:
  - "io.quarkiverse-quarkiverse-parent-10-AUTOBUILD"
  - "org.apache.santuario-xmlsec-2.3.3-AUTOBUILD"
  brewPullActive: false
  buildType: "MVN"
- name: "com.fasterxml-oss-parent-50-AUTOBUILD"
  project: "FasterXML-oss-parent"
  buildScript: "# This build configuration was modified by Autobuilder\n# Autobuilder\
    \ copied this Build Config from BC #11054 rev 2656768\n# This build configuration\
    \ was modified by Autobuilder\n# Autobuilder copied this Build Config from BC\
    \ #11051 rev 2656718\n# This build configuration was modified by Autobuilder\n\
    mvn clean deploy -B -DperformRelease dependency:tree -DaltDeploymentRepository=indy-mvn::${AProxDeployUrl}"
  scmUrl: "https://github.com/FasterXML/oss-parent.git"
  scmRevision: "oss-parent-50"
  environmentName: "OpenJDK 1.8; Mvn 3.6.3"
  brewPullActive: false
  buildType: "MVN"
- name: "io.quarkiverse-quarkiverse-parent-10-AUTOBUILD"
  project: "quarkiverse/quarkiverse-parent"
  buildScript: "# This build configuration was modified by Autobuilder\n# Autobuilder\
    \ copied this Build Config from BC #10142 rev 2651546\n# This build configuration\
    \ was modified by Autobuilder\nmvn clean deploy"
  scmUrl: "https://github.com/quarkiverse/quarkiverse-parent.git"
  scmRevision: "10"
  environmentName: "OpenJDK 11.0; RHEL 8; Mvn 3.8.6; Nodejs 16; npm 8"
  dependencies:
  - "org.jboss-jboss-parent-39-AUTOBUILD"
  brewPullActive: false
  buildType: "MVN"
- name: "org.apache.santuario-xmlsec-2.3.3-AUTOBUILD"
  project: "apache-santuario-xml-security-java"
  buildScript: "# This build configuration was modified by Autobuilder\n# Autobuilder\
    \ copied this Build Config from BC #4880 rev 2586491\nmvn '-Dadditionalparam=-Xdoclint:none'\
    \ '-DperformRelease' '-Dmaven.test.skip=true' 'deploy'"
  scmUrl: "https://github.com/apache/santuario-xml-security-java.git"
  scmRevision: "xmlsec-2.3.3"
  environmentName: "OpenJDK 1.8; Mvn 3.6.3"
  dependencies:
  - "commons-codec-commons-codec-1.15-AUTOBUILD"
  - "org.apache-apache-24-AUTOBUILD"
  brewPullActive: true
  buildType: "MVN"
- name: "org.codehaus.woodstox-stax2-api-4.2.1-AUTOBUILD"
  project: "FasterXML-stax2-api"
  buildScript: "# Autobuilder copied this Build Config from BC #11055 rev 2656769\n\
    # This build configuration was modified by Autobuilder\n# Autobuilder copied this\
    \ Build Config from BC #1554 rev 31334\nmvn '-DperformRelease' 'deploy'"
  scmUrl: "https://github.com/FasterXML/stax2-api.git"
  scmRevision: "0dd8e49d430f23b19a1689adfd7ca9f01841c79b"
  environmentName: "OpenJDK 1.8; Mvn 3.3.9"
  dependencies:
  - "com.fasterxml-oss-parent-38-AUTOBUILD"
  brewPullActive: true
  buildType: "MVN"
- name: "com.fasterxml-oss-parent-38-AUTOBUILD"
  project: "FasterXML-oss-parent"
  buildScript: "# This build configuration was modified by Autobuilder\n# Autobuilder\
    \ copied this Build Config from BC #11056 rev 2656770\n# This build configuration\
    \ was modified by Autobuilder\n# Autobuilder copied this Build Config from BC\
    \ #3599 rev 2547370\nmvn clean deploy -B -DperformRelease dependency:tree -DaltDeploymentRepository=indy-mvn::${AProxDeployUrl}"
  scmUrl: "https://github.com/FasterXML/oss-parent.git"
  scmRevision: "oss-parent-38"
  environmentName: "OpenJDK 1.8; Mvn 3.6.3"
  brewPullActive: true
  buildType: "MVN"
- name: "commons-codec-commons-codec-1.15-AUTOBUILD"
  project: "apache-commons-codec"
  buildScript: "# This build configuration was modified by Autobuilder\n# Autobuilder\
    \ copied this Build Config from BC #1624 rev 2531174\nmvn '-DskipTests' '-DperformRelease'\
    \ '-Drat.skip' 'deploy'"
  scmUrl: "git+ssh://code.engineering.redhat.com/apache/commons-codec.git"
  scmRevision: "rel/commons-codec-1.15"
  environmentName: "OpenJDK 1.8; Mvn 3.6.3"
  dependencies:
  - "org.apache.commons-commons-parent-52-AUTOBUILD"
  brewPullActive: true
  buildType: "MVN"
- name: "org.apache-apache-24-AUTOBUILD"
  project: "apache-maven-pom"
  buildScript: "# This build configuration was modified by Autobuilder\n# Autobuilder\
    \ copied this Build Config from BC #1002 rev 2589313\nmvn '-DperformRelease' 'deploy'"
  scmUrl: "https://gitbox.apache.org/repos/asf/maven-apache-parent.git"
  scmRevision: "apache-24"
  environmentName: "OpenJDK 1.8; Mvn 3.3.9"
  brewPullActive: true
  buildType: "MVN"
- name: "org.jboss-jboss-parent-39-AUTOBUILD"
  project: "jboss-jboss-parent-pom"
  buildScript: "# This build configuration was modified by Autobuilder\n# Autobuilder\
    \ copied this Build Config from BC #10296 rev 2651856\n# This build configuration\
    \ was modified by Autobuilder\nmvn '-DperformRelease' '-Dinsecure.repositories=WARN'\
    \ 'deploy'"
  scmUrl: "https://github.com/jboss/jboss-parent-pom.git"
  scmRevision: "jboss-parent-39"
  environmentName: "OpenJDK 1.8; Mvn 3.3.9"
  alignmentParameters:
  - "-DexcludedScopes=compile,provided,runtime,test -DpluginOverride.*:*@*= -DrepoReportingRemoval=true\
    \ -DprojectMetaSkip=true -DprojectSrcSkip=false"
  brewPullActive: false
  buildType: "MVN"
- name: "org.apache.commons-commons-parent-52-AUTOBUILD"
  project: "apache-commons-parent"
  buildScript: "# This build configuration was modified by Autobuilder\n# Autobuilder\
    \ copied this Build Config from BC #9531 rev 2652273\n# This build configuration\
    \ was modified by Autobuilder\nmvn '-Dadditionalparam=-Xdoclint:none' '-Drat.skip'\
    \ 'deploy'"
  scmUrl: "https://github.com/apache/commons-parent.git"
  scmRevision: "rel/commons-parent-52"
  environmentName: "OpenJDK 1.8; Mvn 3.5.4; Golang"
  dependencies:
  - "org.apache-apache-23-AUTOBUILD"
  brewPullActive: true
  buildType: "MVN"
- name: "org.apache-apache-23-AUTOBUILD"
  project: "apache-maven-pom"
  buildScript: "# This build configuration was modified by Autobuilder\n# Autobuilder\
    \ copied this Build Config from BC #9534 rev 2652945\n# This build configuration\
    \ was modified by Autobuilder\nmvn '-DperformRelease' 'deploy'"
  scmUrl: "https://gitbox.apache.org/repos/asf/maven-apache-parent.git"
  scmRevision: "apache-23"
  environmentName: "OpenJDK 1.8; Mvn 3.3.9"
  alignmentParameters:
  - "-Dmanipulation.disable=false"
  brewPullActive: true
  buildType: "MVN"
outputPrefixes:
  releaseFile: "ab-example"
  releaseDir: "ab-example"
flow:
  licensesGeneration:
    strategy: "IGNORE"
  repositoryGeneration:
    strategy: "IGNORE"
    additionalArtifacts: []
    externalAdditionalArtifacts: []
    externalAdditionalConfigs: []
    excludeArtifacts: []
    sourceBuilds: []
    excludeSourceBuilds: []
    filterArtifacts: []
    includeJavadoc: false
    includeLicenses: false
    includeMavenMetadata: false
    ignored: []
    stages: []
    parameters: {}
    steps: []
  javadocGeneration:
    strategy: "IGNORE"
    sourceBuilds: []
    customPmeParameters: []
    alignmentParameters: []
  sourcesGeneration:
    strategy: "IGNORE"
    sourceBuild: null
    sourceArtifact: null
    whitelistedArtifacts: []
    additionalExternalSources: []
addons:
  notYetAlignedFromDependencyTree: null

