---
product:
  name: "Camel Extensions for Quarkus Third Party Components"
  abbreviation: "quarkus-cxf-third-party"
  stage: "GA"
  issueTrackerUrl: "https://issues.redhat.com/projects/CEQ"
version: "2.13.3"
milestone: "CR2"
group: "CXF Extensions for Quarkus Third Party Components"
defaultBuildParameters:
  brewPullActive: false
builds:
- name: "com.fasterxml.woodstox-woodstox-core-6.5.1-AUTOBUILD"
  project: "FasterXML-woodstox"
  buildScript: "# This build configuration was modified by Autobuilder\n# Autobuilder\
    \ copied this Build Config from BC #10638 rev 2651661\nmvn '-DskipTests' '-DperformRelease'\
    \ '-Dadditionalparam=-Xdoclint:none' -DaltDeploymentRepository=indy-mvn::${AProxDeployUrl}\
    \ 'deploy'"
  scmUrl: "https://github.com/FasterXML/woodstox.git"
  scmRevision: "woodstox-core-6.5.1"
  environmentName: "OpenJDK 11.0.10+9; Mx 5.259.0; Mvn 3.6.0"
  dependencies:
  - "com.fasterxml-oss-parent-50-AUTOBUILD"
  - "org.codehaus.woodstox-stax2-api-4.2.1-AUTOBUILD"
  brewPullActive: false
  buildType: "MVN"
- name: "io.quarkiverse.cxf-quarkus-cxf-bom-1.5.14-AUTOBUILD"
  project: "quarkiverse/quarkus-cxf"
  buildScript: "# This build configuration was modified by Autobuilder\n# Autobuilder\
    \ copied this Build Config from BC #11048 rev 2656673\nmvn clean deploy -DskipTests"
  scmUrl: "https://github.com/quarkiverse/quarkus-cxf.git"
  scmRevision: "1.5.14"
  environmentName: "OpenJDK 11.0; RHEL 8; Mvn 3.8.6; gcc-cpp; make"
  buildPodMemory: 12.0
  brewPullActive: false
  buildType: "MVN"
- name: "com.fasterxml-oss-parent-50-AUTOBUILD"
  project: "FasterXML-oss-parent"
  buildScript: "# This build configuration was modified by Autobuilder\n# Autobuilder\
    \ copied this Build Config from BC #11051 rev 2656718\n# This build configuration\
    \ was modified by Autobuilder\nmvn clean deploy -B -DperformRelease dependency:tree\
    \ -DaltDeploymentRepository=indy-mvn::${AProxDeployUrl}"
  scmUrl: "https://github.com/FasterXML/oss-parent.git"
  scmRevision: "oss-parent-50"
  environmentName: "OpenJDK 1.8; Mvn 3.6.3"
  brewPullActive: false
  buildType: "MVN"
- name: "org.codehaus.woodstox-stax2-api-4.2.1-AUTOBUILD"
  project: "FasterXML-stax2-api"
  buildScript: "# This build configuration was modified by Autobuilder\n# Autobuilder\
    \ copied this Build Config from BC #1554 rev 31334\nmvn '-DperformRelease' 'deploy'"
  scmUrl: "https://github.com/FasterXML/stax2-api.git"
  scmRevision: "0dd8e49d430f23b19a1689adfd7ca9f01841c79b"
  environmentName: "OpenJDK 1.8; Mvn 3.3.9"
  dependencies:
  - "com.fasterxml-oss-parent-38-AUTOBUILD"
  brewPullActive: true
  buildType: "MVN"
- name: "com.fasterxml-oss-parent-38-AUTOBUILD"
  project: "FasterXML-oss-parent"
  buildScript: "# This build configuration was modified by Autobuilder\n# Autobuilder\
    \ copied this Build Config from BC #3599 rev 2547370\nmvn clean deploy -B -DperformRelease\
    \ dependency:tree -DaltDeploymentRepository=indy-mvn::${AProxDeployUrl}"
  scmUrl: "https://github.com/FasterXML/oss-parent.git"
  scmRevision: "oss-parent-38"
  environmentName: "OpenJDK 1.8; Mvn 3.6.3"
  brewPullActive: true
  buildType: "MVN"
outputPrefixes:
  releaseFile: "ab-example"
  releaseDir: "ab-example"
flow:
  licensesGeneration:
    strategy: "IGNORE"
  repositoryGeneration:
    strategy: "IGNORE"
    additionalArtifacts: []
    externalAdditionalArtifacts: []
    externalAdditionalConfigs: []
    excludeArtifacts: []
    sourceBuilds: []
    excludeSourceBuilds: []
    filterArtifacts: []
    includeJavadoc: false
    includeLicenses: false
    includeMavenMetadata: false
    ignored: []
    stages: []
    parameters: {}
    steps: []
  javadocGeneration:
    strategy: "IGNORE"
    sourceBuilds: []
    customPmeParameters: []
    alignmentParameters: []
  sourcesGeneration:
    strategy: "IGNORE"
    sourceBuild: null
    sourceArtifact: null
    whitelistedArtifacts: []
    additionalExternalSources: []
addons:
  notYetAlignedFromDependencyTree: null

